<?php
function hello_drupal_expage() {
//  return print_r (phpinfo());
  return 'Hello Drul1111 !';
}

function hello_drupal_menu() {
  $items['hello_dru'] = array(
    'title' => 'Hello Dru!',
    'description' => 'First page',
    'page callback' => 'hello_drupal_expage',
    'access callback' => TRUE,
//    'access arguments' => array(1, 'access administration menu'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

