<?php

// Implements hook_menu()

function send_mail_menu() {
  $items = array();
  $items['send_mail/form'] = array(
    'title' => 'Send mail page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('send_mail_form'),
    'access arguments' => array('post comments'),
  );
  $items['send_mail/admin'] = array(
    'title' => 'Send mail admin page',
    'page callback' => 'send_mail_admin',
    'page arguments' => array(''),
    'access arguments' => array('access administration menu'),
  );
  return $items;
}

function send_mail_admin() {

  $header = array(t('ID'), t('Email'), t('Subject'), t('From user'), t('Date'));
  $rows = array();

  $query = db_select('send_mail_table', 's')
    ->fields('s')
    ->execute();

  while ($value = $query->fetchAssoc()) {

    $user = user_load($value['uid']);
    $username = $user->name;

    $rows[] = array(
      $value['id'],
      $value['email'],
      $value['subject'],
      $username,
      //$value['uid'],
      format_date($value['sended_at'], 'long')
    );
  }

  return theme('table', array('header' => $header, 'rows' => $rows));

}

function send_mail_theme() {
  return array(
    'admin_page_template' => array(
      'variables' => array(
        'body' => NULL,
        'title' => NULL,
      ),
    ),
  );
}


function theme_admin_page_template($variables) {
  $output = '<div class="custom-template-wrapper">';
  $output .= '<div class="title">';
  $output .= $variables['title'];
  $output .= '</div>';
  $output .= '<div class="body">';
  $output .= $variables['body'];
  $output .= '</div>';
  $output .= '</div>';
  return $output;
}


function send_mail_form() {

  $form = array();

  $form['to'] = array(
    '#type' => 'fieldset',
    '#title' => 'To',
  );

  $form['to']['greeting'] = array(
    '#type' => 'select',
    '#options' => array('Sir', 'Mr.', 'Madam', 'Ms.'),
    '#required' => TRUE,
  );

  $form['to']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#size' => 20,
    '#required' => TRUE,
  );

  $form['to']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#size' => 20,
    '#required' => TRUE,
  );

  $form['message'] = array(
    '#type' => 'fieldset',
    '#title' => 'Message',
  );

  $form['message']['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#size' => 20,
    '#required' => TRUE,
  );


  $form['message']['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Body'),
    '#size' => 200,
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send message'),
  );
  return $form;
}

// Validate function for send_mail_form
function send_mail_form_validate($form, &$form_state) {

  $mail = $form_state['values']['email'];
  if (!valid_email_address($mail)) {

    form_set_error('email', t('The email address appears to be invalid.'));
  }
}

function send_mail_form_submit($form, &$form_state) {

  global $user;
  $uid = $user->uid;
  $user_name = $user->name;
  $values = $form_state['values'];
  $values['greeting'] = $form['to']['greeting']['#options'][$form_state['values']['greeting']];
  // $values['body'] = $values['body']['value'];

  $to = $values['email'];


  $params = array(
    'subject' => $values['subject'],
    'body' => $values['body'],
    'greeting' => $values['greeting'],
    'name' => $values['name'],
    'username' => $user_name,
    'sended_at' => REQUEST_TIME,
  );


//  drupal_mail($module, $key, $to, $language, $params = array(), $from = NULL, $send = TRUE)
  if (drupal_mail('send_mail', 'page_mail', $to, language_default(), $params)) {

    $query = db_insert('send_mail_table')
      ->fields(array('id', 'greeting', 'name', 'email', 'subject', 'body', 'uid', 'sended_at'))
      ->values(array(
        'id' => NULL,
        'greeting' => $values['greeting'],
        'name' => $values['name'],
        'email' => $values['email'],
        'subject' => $values['subject'],
        'body' => $values['body'],
        'uid' => $uid,
        'sended_at' => REQUEST_TIME
      ))
      ->execute();
    if ($query > 0) {
      drupal_set_message(t('Success: the message was sent and record to the base.'), 'status');
    } else {
      drupal_set_message(t('Success: the message was sent, but was not record to the base.'), 'status');
    }

  } else drupal_set_message(t('Fail: the message was not sent.'), 'status');

}

function send_mail_mail($key, &$message, $params) {

  $language = $message['language'];

  $variables = array(
    '!site-name' => variable_get('site_name', 'Drupal'),
    '!subject' => $params['subject'],
    '!greeting' => 'Hello, ' . $params['greeting'] . ' ' . $params['name'] . '! ',
    '!body' => $params['body'],
    'sended_at' => format_date($params['sended_at'], 'long'),
  );
  switch ($key) {
    case 'page_mail':
      $message['subject'] .= t($variables['!subject'], array('langcode' => $language->language));
      $message['body'][] .= t($variables['!greeting'], array('langcode' => $language->language));
      $message['body'][] .= t($variables['!body'], array('langcode' => $language->language));
      $message['body'][] .= t('This message was sent from ' . $variables['!site-name'], array('langcode' => $language->language));
      $message['body'][] .= t('By user ' . $params['username'], array('langcode' => $language->language));
      $message['body'][] .= t('At ' . $variables['sended_at'] . '.', array('langcode' => $language->language));
      break;
  }
}
