<?php
//
//function send_mail_menu() {
//  $items['send_mail'] = array(
//    'title' => 'Send mail form',
////  'description' => 'Send mail form',
//    'page callback' => 'send_mail_page',
//    'access callback' => TRUE,
////  'access arguments' => array(1, 'access administration menu'),
//    'type' => MENU_CALLBACK
//  );
//  return $items;
//}
//
//function send_mail_form($form_state) {
//  // send_mail log settings:
////  $options = array('1' => t('Enabled'), '0' => t('Disabled'));
//  $form['send_mail'] = array(
//    '#type' => 'fieldset',
//    '#title' => t('send mail settings'),
//    '#tree' => TRUE,
//  );
//  $form['send_mail']['log'] = array(
//    '#type' => 'radios',
//    '#title' => t('Log'),
//    '#default_value' =>  variable_get('log', 0),
//    '#options' => $options,
//    '#description' => t('The log.'),
//  );
//  $period = drupal_map_assoc(array(3600, 10800, 21600, 32400, 43200, 86400, 172800, 259200, 604800, 1209600, 2419200, 4838400, 9676800), 'format_interval');
//  $form['send_mail']['timer'] = array(
//    '#type' => 'select',
//    '#title' => t('Discard logs older than'),
//    '#default_value' => variable_get('timer', 259200),
//    '#options' => $period,
//    '#description' => t('The timer.'),
//  );
//  // Description
//  $form['details'] = array(
//    '#type' => 'fieldset',
//    '#title' => t('Details'),
//    '#collapsible' => TRUE,
//    '#collapsed' => TRUE,
//  );
//  $form['details']['description'] = array(
//    '#type' => 'textarea',
//    '#title' => t('Describe it'),
//    '#default_value' =>  variable_get('description', ''),
//    '#cols' => 60,
//    '#rows' => 5,
//    '#description' => t('Log description.'),
//  );
//  $form['details']['admin'] = array(
//    '#type' => 'checkbox',
//    '#title' => t('Only admin can view'),
//    '#default_value' => variable_get('admin', 0),
//  );
//  $form['name'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Name'),
//    '#size' => 30,
//    '#maxlength' => 64,
//    '#description' => t('Enter the name for this group of settings'),
//  );
//  $form['hidden'] = array('#type' => 'value', '#value' => 'is_it_here');
//  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
//  return $form;
//}
//
//function send_mail_page() {
//  return drupal_get_form('send_mail');
//}
//
//function theme_send_mail($form) {
//  $output = '';
//  $output .= drupal_render($form['name']);
//  $output .= '<div class="foo">';
//  $output .= drupal_render($form['send_mail']);
//  $output .= '<div class="bar">';
//  $output .= drupal_render($form['details']);
//  $output .= '</div></div>';
//  $output .= drupal_render($form);
//  return $output;
//}
//
//function send_mail_validate($form, &$form_state) {
//  if ($form_state['values']['name'] == '') {
//    form_set_error('', t('You must select a name for this group of settings.'));
//  }
//}

// Implements hook_menu()

function send_mail_menu() {
  $items = array();
  $items['send_mail_page'] = array(
    'title' => 'Send mail page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('send_mail_form'),
    'access arguments' => array('post comments'),
  );
  $items['send_mail_admin_page'] = array(
    'title' => 'Send mail admin page',
    'page callback' => 'send_mail_admin',
    'page arguments' => array(''),
    'access arguments' => array('access administration menu'),
  );

  return $items;
}

function send_mail_admin() {
  






  return 'Admin page';
}

function send_mail_form() {

  $form = array();

  $form['to'] = array(
    '#type' => 'fieldset',
    '#title' => 'To',
  );

  $form['to']['greeting'] = array(
    '#type' => 'select',
    '#options' => array('Sir', 'Mr.', 'Madam', 'Ms.'),
    '#required' => TRUE,
  );

  $form['to']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#size' => 20,
    '#required' => TRUE,
  );

  $form['to']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#size' => 20,
    '#required' => TRUE,
  );

  $form['message'] = array(
    '#type' => 'fieldset',
    '#title' => 'Message',
  );

  $form['message']['subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#size' => 20,
    '#required' => TRUE,
  );


  $form['message']['body'] = array(
    '#type' => 'text_format',
    '#title' => t('Body'),
    '#size' => 200,
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send message'),
  );
  return $form;
}

// Validate function for send_mail_form
function send_mail_form_validate($form, &$form_state) {

  $mail = $form_state['values']['email'];
  if (!valid_email_address($mail)) {

    form_set_error('email', t('The email address appears to be invalid.'));
  }
}

function send_mail_form_submit($form, &$form_state) {

  global $user;
  $uid = $user->uid;
  $to = $form_state['values']['email'];

  $params = array(
    'subject' => $form_state['values']['subject'],
    'body' => $form_state['values']['body']['value'],
    'greeting' => $form['to']['greeting']['#options'][$form_state['values']['greeting']],
    'name' => $form_state['values']['name']
  );

  $values = $form_state['values'];
  $to = $values['email'];
  $values['greeting'] = $form['to']['greeting']['#options'][$form_state['values']['greeting']];
//  drupal_mail($module, $key, $to, $language, $params = array(), $from = NULL, $send = TRUE)
  drupal_mail('send_mail', 'page_mail', $to, language_default(), $values);

  db_insert('send_mail_table')
    ->fields(array('id', 'greeting', 'name', 'email', 'subject', 'body', 'uid', 'sended_at'))
    ->values(array(
      'id' => NULL,
      'greeting' => $values['greeting'],
      'name' => $values['name'],
      'email' => $values['email'],
      'subject' => $values['subject'],
      'body' => $values['body']['value'],
      'uid' => $uid,
      'sended_at' => REQUEST_TIME
    ))
    ->execute();

  drupal_set_message(t('Success: the message was sent.'), 'status');

}

function send_mail_mail($key, &$message, $params) {

  $language = $message['language'];

  $variables = array(
  //'!site-name' => variable_get('site_name', 'Drupal'),
    '!subject' => $params['subject'],
    '!greeting' => 'Hello, ' . $params['greeting'] . ' ' . $params['name'] . '! ',
    '!body' => $params['body']['value'],
  );
  switch ($key) {
    case 'page_mail':
      $message['subject'] .= t($variables['!subject'], array('langcode' => $language->language));
      $message['body'][] .= t($variables['!greeting'], array('langcode' => $language->language));
      $message['body'][] .= t($variables['!body'], array('langcode' => $language->language));
      break;
  }
}
