<?php
/**
 * Implements hook_menu().
 */

function charts_menu() {
  $items['example-charts'] = array(
    'title' => 'Example',
    'page callback' => 'charts_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Callback function for menu item.
 */
function charts_page() {
  $data = array(
    array('fruit' => 'apple', 'votes' => 16),
    array('fruit' => 'mango', 'votes' => 10),
    array('fruit' => 'banana', 'votes' => 34),
    array('fruit' => 'peach', 'votes' => 20),
    array('fruit' => 'orange', 'votes' => 15),
  );

  $options_pie = array(
    'title' => 'Favourite fruits',
    'fields' => array(
      'votes' => array(
        'label' => t('Votes'),
        'enabled' => TRUE,
      ),
    ),
    'xAxis' => array(
      'labelField' => 'fruit',
    ),
    'data' => $data,
    'type' => 'pie',
  );

  $options_column = array(
    'title' => 'Favourite fruits',
    'fields' => array(
      'votes' => array(
        'label' => t('Votes'),
        'enabled' => TRUE,
      ),
    ),
    'xAxis' => array(
      'labelField' => 'fruit',
    ),
    'data' => $data,
    'type' => 'column',
  );

//  $options_bar = array(
//    'title' => 'Favourite fruits',
//    'fields' => array(
//      'votes' => array(
//        'label' => t('Votes'),
//        'enabled' => TRUE,
//      ),
//    ),
//    'xAxis' => array(
//    'labelField' => 'fruit',
//    ),
//    'data' => $data,
//    'type' => '',
//  );

  $options_line = array(
    'title' => 'Favourite fruits',
    'fields' => array(
      'votes' => array(
        'label' => t('Votes'),
        'enabled' => TRUE,
      ),
    ),
    'xAxis' => array(
      'labelField' => 'fruit',
    ),
    'data' => $data,
    'type' => 'line',
  );



  $build['line'] = array(
    '#theme' => 'visualization',
    '#options' => $options_line,
  );


//  $build['bar'] = array(
//    '#theme' => 'visualization',
//    '#options' => $options_bar,
//  );


  $build['column'] = array(
    '#theme' => 'visualization',
    '#options' => $options_column,
  );


  $build['pie'] = array(
    '#theme' => 'visualization',
    '#options' => $options_pie,
  );


  return $build;
}